WebApplicationQLSV/Models/Diem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationQLSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int ID { get; set; }
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> DiemGK { get; set; }
        public Nullable<double> DiemCK { get; set; }
        public Nullable<double> DiemTB { get; set; }
    }
}

WebApplicationQLSV/Controllers/DiemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationQLSV.Models;

namespace WebApplicationQLSV.Controllers
{
    public class DiemController : Controller
    {
        // GET: Diem
      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            using (DBModelQLSV db = new DBModelQLSV())
            {
                List<Diem> empList = db.Diems.ToList<Diem>();
                return Json(new { data = empList }, JsonRequestBehavior.AllowGet);
            }
        }

        // Lấy dữ liệu 
        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Diem());
            else
            {
                using (DBModelQLSV db = new DBModelQLSV())
                {
                    return View(db.Diems.Where(x => x.ID == id).FirstOrDefault<Diem>());
                }
            }
            //return View(new MonHoc());  
        }
        // Tạo dữ liệu mới
        [HttpPost]
        public ActionResult AddOrEdit(Diem emp)
        {
            using (DBModelQLSV db = new DBModelQLSV())
            {

                if (emp.ID == 0)
                {
                    db.Diems.Add(emp);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(emp).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (DBModelQLSV db = new DBModelQLSV())
            {
                Diem emp = db.Diems.Where(x => x.ID == id).FirstOrDefault<Diem>();
                db.Diems.Remove(emp);
                db.SaveChanges();
                return Json(new { success = true, message = "Đã xóa thành công!" }, JsonRequestBehavior.AllowGet);
            }
        }



    }
}

WebApplicationQLSV/Views/Diem/AddOrEdit.cshtml
@model WebApplicationQLSV.Models.Diem
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Diem", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.ID)
    <div class="form-group mt-3">
        @Html.LabelFor(model => model.MaSV, new { @class = "control-label" })
        @Html.EditorFor(model => model.MaSV, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaSV)
    </div>
    <div class="form-group mt-3 w-auto">
        @Html.LabelFor(model => model.TenSV, new { @class = "control-label" })
        @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TenSV)
    </div>
    <div class="form-group mt-3">
        @Html.LabelFor(model => model.MaMH, new { @class = "control-label" })
        @Html.EditorFor(model => model.MaMH, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="form-group mt-3">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row">

            <div class="col-sm-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.DiemGK, new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.DiemGK, new { htmlAttributes = new { @class = "form-control form-input" } })
                        @Html.ValidationMessageFor(model => model.DiemGK, "", new { @class = "text-danger" })
                        <span class="input-group-addon invisible"><i class="glyphicon glyphicon-th"></i></span>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="form-group mt-3">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row">

            <div class="col-sm-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.DiemCK, new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.DiemCK, new { htmlAttributes = new { @class = "form-control form-input" } })
                        @Html.ValidationMessageFor(model => model.DiemCK, "", new { @class = "text-danger" })
                        <span class="input-group-addon invisible"><i class="glyphicon glyphicon-th"></i></span>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="form-group mt-3">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row">

            <div class="col-sm-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.DiemTB, new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.DiemTB, new { htmlAttributes = new { @class = "form-control form-input" } })
                        @Html.ValidationMessageFor(model => model.DiemTB, "", new { @class = "text-danger" })
                        <span class="input-group-addon invisible"><i class="glyphicon glyphicon-th"></i></span>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="form-group  mt-3 mt-3">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn" />
    </div>
}

WebApplicationQLSV/Views/Diem/Index.cshtml
@{
    ViewBag.Title = "Danh Sách Điểm ";
}

<h2> Quản Lý Điểm   </h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Diem")')"><i class="fa fa-plus"></i> Add New</a>
<table id="diemTable" class="table table-striped table-bordered border" style="width:100%">
    <thead>
        <tr>
            <th>MaSV</th>
            <th>TenSV</th>
            <th>MaMH</th>
            <th>DiemGK</th>
            <th>DiemCK</th>
            <th>DiemTB</th>
            <th></th>
        </tr>
    </thead>
</table>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />
<link href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />


@section scripts{
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

    <script>

       var Popup, dataTable;
        $(document).ready(function () {
            dataTable = $("#diemTable").DataTable({
                "ajax": {
                    "url": "/Diem/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "MaSV" },
                    { "data": "TenSV" },
                    { "data": "MaMH" },
                    { "data": "DiemGK" },
                    { "data": "DiemCK" },
                    { "data": "DiemTB" },

                    {"data":"ID" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit", "Diem")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"250px"
                    }

                ],

                "language": {

                    "emptyTable" : "No data found, Please click on <b>Add New</b> Button"
                }
            });
        });
        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Điền chi tiết thông tin điểm ',
                        height: 500,
                        width: 700,
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }

                    });
                });
        }
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }
                });
            }
            return false;
        }
         function Delete(id) {
             if (confirm('Are You Sure to Delete this Diem Record ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "Diem")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }

    </script>
}