WebApplicationQLSV/Models/SinhVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationQLSV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string MaSV { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string TenSV { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string Lop { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string GioiTinh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string QueQuan { get; set; }
        public string DanToc { get; set; }
    }
}

WebApplicationQLSV/Controllers/SinhVienController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationQLSV.Models;


namespace WebApplicationQLSV.Controllers
{
    public class SinhVienController : Controller
    {
        // GET: SinhVien
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            using (DBModelQLSV db = new DBModelQLSV())
            {
                List<SinhVien> empList = db.SinhViens.ToList <SinhVien>();
                return Json(new { data = empList }, JsonRequestBehavior.AllowGet);
            }
        }

        // Lấy dữ liệu 
        [HttpGet]
        public ActionResult AddOrEdit( int id = 0) {
            if (id == 0)
                return View(new SinhVien());
            else
            {
                using (DBModelQLSV db = new DBModelQLSV())
                {
                    return View(db.SinhViens.Where(x => x.ID == id).FirstOrDefault<SinhVien>());
                }
            }
            //return View(new Employee());  
        }
        // Tạo dữ liệu mới
        [HttpPost]
        public ActionResult AddOrEdit(SinhVien emp)
        {
            using (DBModelQLSV db = new DBModelQLSV())
            {

                if (emp.ID == 0)
                {
                    db.SinhViens.Add(emp);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(emp).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (DBModelQLSV db = new DBModelQLSV())
            {
                SinhVien emp = db.SinhViens.Where(x => x.ID == id).FirstOrDefault<SinhVien>();
                db.SinhViens.Remove(emp);
                db.SaveChanges();
                return Json(new { success = true, message = "Đã xóa thành công!" }, JsonRequestBehavior.AllowGet);
            }
        }



    }
}

WebApplicationQLSV/Views/SinhVien/AddOrEdit.cshtml
@model WebApplicationQLSV.Models.SinhVien
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "SinhVien", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.ID)
    <div class="form-group mt-3">
        @Html.LabelFor(model => model.MaSV, new { @class = "control-label" })
        @Html.EditorFor(model => model.MaSV, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaSV)
    </div>
    <div class="form-group mt-3 w-auto">
        @Html.LabelFor(model => model.TenSV, new { @class = "control-label" })
        @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TenSV)
    </div>
    <div class="form-group mt-3">
        @Html.LabelFor(model => model.Lop, new { @class = "control-label" })
        @Html.EditorFor(model => model.Lop, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group mt-3">
        @Html.LabelFor(model => model.GioiTinh, new { @class = "control-label" })
        @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group mt-3">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row">
            
            <div class="col-sm-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.NamSinh, new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.NamSinh, new { htmlAttributes = new { @class = "form-control form-input" } })
                        @Html.ValidationMessageFor(model => model.NamSinh, "", new { @class = "text-danger" })
                        <span class="input-group-addon invisible"><i class="glyphicon glyphicon-th"></i></span>
                    </div>
                </div>
            </div>
        </div>

    </div>
    @*<div class="form-group mt-3">

        @Html.LabelFor(model => model.Email, new { @class = "control-label" })

        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })

    </div>*@
    <div class="form-group mt-3">

        @Html.LabelFor(model => model.QueQuan, new { @class = "control-label" })

        @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })

    </div>
    <div class="form-group mt-3">

        @Html.LabelFor(model => model.DanToc, new { @class = "control-label" })

        @Html.EditorFor(model => model.DanToc, new { htmlAttributes = new { @class = "form-control" } })

    </div>
    <div class="form-group  mt-3 mt-3">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn" />
    </div>
}

WebApplicationQLSV/Views/SinhVien/Index.cshtml
@{
    ViewBag.Title = "Danh Sách Sinh Viên";
}

<h2> Quản Lý Sinh Viên  </h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","SinhVien")')"><i class="fa fa-plus"></i> Add New</a>
<table id="sinhVienTable" class="table table-striped border table-bordered  " style="width:100%">
   
        <thead>
            <tr>
                <th scope="col">MaSV</th>
                <th scope="col">TenSV</th>
                <th scope="col">Lop</th>
                <th scope="col">GioiTinh</th>
                <th scope="col">NamSinh</th>
                <th scope="col">QueQuan</th>
                <th scope="col">DanToc</th>
                <th scope="col"> </th>
            </tr>
        </thead>
    </table>


    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"/>
    <link href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />


    @section scripts{
        <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

        <script>

       var Popup, dataTable;
        $(document).ready(function () {
            dataTable = $("#sinhVienTable").DataTable({
                "ajax": {
                    "url": "/SinhVien/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "MaSV" },
                    { "data": "TenSV" },
                    { "data": "Lop" },
                    { "data": "GioiTinh" },
                    { "data": "NamSinh" },
                    { "data": "QueQuan" },
                    { "data": "DanToc" },
                    {"data":"ID" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit", "SinhVien")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"250px"
                    }

                ],

                "language": {

                    "emptyTable" : "No data found, Please click on <b>Add New</b> Button"
                }
            });
        });
        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Điền chi tiết Sinh Viên',
                        height: 500,
                        width: 700,
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }

                    });
                });
        }
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }
                });
            }
            return false;
        }
         function Delete(id) {
             if (confirm('Are You Sure to Delete this SinhVien Record ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "SinhVien")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }

        </script>
    }